###Index
GET http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2ODk4MjAwNDd9.wu0-MxfEnqTlWTbI4GGYdKA1jysR8XUpqPQ0vzZLtBQ


###CREATE
POST http://localhost:3000/products.json
Content-Type: application/json
Authorization: Bearer veyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2ODk5ODQzNzF9.XfAkMJiJ9CIZvSd5iXvQJmQNHZwBzZya077yESdIMrE
{
  "name": "3 Piece Dark Plate",
  "price": 12,
  "image_url": "https://s.hdnux.com/photos/01/11/42/67/19279343/8/2400x0.jpg",
  "description": "Crispy, tasty, delicious! Fried chicken with 2 sides!"
}

###UPDATE
PATCH http://localhost:3000/products/1.json
Content-Type: application/json

{"price": 55}

###DESTROY
DELETE http://localhost:3000/products/1.json

###Create User
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Amelie",
  "email": "amelie@info.com",
  "password": "password1",
  "password_confirmation": "password1"
}

###Login time
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email":"amelie@info.com",
  "password": "password1"
}

###Test Create Order
POST http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2ODk5ODQzNzF9.XfAkMJiJ9CIZvSd5iXvQJmQNHZwBzZya077yESdIMrE
Content-Type: application/json

{
  "product_id": 2,
  "quantity": 1,
}
  

###Show Order
GET http://localhost:3000/orders/4.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2ODk5ODQzNzF9.XfAkMJiJ9CIZvSd5iXvQJmQNHZwBzZya077yESdIMrE

###Index Order
GET http://localhost:3000/orders.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2ODk5ODQzNzF9.XfAkMJiJ9CIZvSd5iXvQJmQNHZwBzZya077yESdIMrE
