GET http://localhost:3000/products.json


###CREATE
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "3 Piece Dark Plate",
  "price": 12,
  "image_url": "https://s.hdnux.com/photos/01/11/42/67/19279343/8/2400x0.jpg",
  "description": "Crispy, tasty, delicious! Fried chicken with 2 sides!"
}

###UPDATE
PATCH http://localhost:3000/products/1.json
Content-Type: application/json

{"price": 55}

###DESTROY
DELETE http://localhost:3000/products/1.json